services:
    payplug.payment:
        class: Alcalyn\PayplugBundle\Services\PayplugPaymentService
        arguments: [%payplug.account.url%, %payplug.account.yourPrivateKey%, @router]
        
    payplug.ipn:
        class: Alcalyn\PayplugBundle\Services\PayplugIPNService
        arguments: [%payplug.account.payplugPublicKey%]
